### ISSUE TITLE
关于部署

### ISSUE THREAD

**Issue by wavecao** [ss098/work#1]
请问如何在自己的域名上部署这个工具？

**Comment by ss098** [comment]
这是一个 Laravel 应用，可以参照文档的部署一章进行部署。

https://learnku.com/docs/laravel/5.8/deployment/3884

另外 ... 你的学校 / 组织也有收集截图的任务吗？

**Comment by wavecao** [comment]
> 这是一个 Laravel 应用，可以参照文档的部署一章进行部署。
> 
> https://learnku.com/docs/laravel/5.8/deployment/3884
> 
> 另外 ... 你的学校 / 组织也有收集截图的任务吗？

是啊，特别厌烦这个东西，但又不得不做，多谢你的工具
