### ISSUE TITLE
希望增加多种文件的上传

### ISSUE THREAD

**Issue by lunarbunnys** [ss098/work#16]
感谢大大能够这么有心开发出个偷懒的好东西（手动狗头），我校团委有时候还让交些思想报告什么的，如果能加上excel，word，zip什么的文件的上传和整理就更棒了，还请考虑下~

**Comment by ss098** [comment]
感谢反馈，如果有时间的话可能会改进这项功能。

**Comment by ss098** [comment]
你好，现已支持任意拓展格式附件上传。
