### ISSUE TITLE
宝塔面板报错

### ISSUE THREAD

**Issue by if1y** [ss098/work#17]
提示没有 /vendor/autoload.php
然后我看了下确实没有
但是index里面这个是require的。。。。

**Comment by ss098** [comment]
需要使用 composer 安装依赖：

    composer install

然后安装 nodejs 依赖：

    npm install
    npm run production

**Comment by if1y** [comment]
😅 谢谢解答，刚换的服务器比较渣，才composer 就被 killed 了，放弃挣扎。。。。
