### ISSUE TITLE
500错误求救

### ISSUE THREAD

**Issue by Oohuo** [ss098/work#20]

**Comment by Oohuo** [comment]
.env文件。
解决了此问题

**Comment by Oohuo** [comment]
然后又遇到了一个新问题，部署好之后我不能创建额

**Comment by ss098** [comment]
请附上详细的说明，是什么不能创建？

**Comment by Oohuo** [comment]
就很蠢，以为部署好就可以运行.问题1)是.env，2)我并没有建数据库。
解决方法：1）因为没用过这个东西，找了很多方法，最后直接google这个文件是什么才解决。

2）我抓了几十个您网站以及我自己本地的数据包看看是什么问题，然后我在数据包的响应里面发现了sql报错，而且附带有完整信息，建库后正常。

最后：很感谢大佬（18岁的高级工程师啊 ，Orz）的项目。
