### ISSUE TITLE
Word，PPT，Excel文件上传后无法打开

### ISSUE THREAD

**Issue by Oohuo** [ss098/work#22]
Word，PPT，Excel文件上传后无法打开
尝试其他文件（txt，java,cpp等）上传下载后均乱码

**Comment by ss098** [comment]
已经修改为兼容任意文件格式的正确正则表达式。

**Comment by Oohuo** [comment]
你好，很抱歉再次打扰
刚才重新测试了6类文件sql\cpp\java\word\excel\ppt
Word文档以及PPT上传会发生数据丢失，文件上传后大小为0
其他文件正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cenegd"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 中午1:49
收件人:&nbsp;"ss098/work"<work@noreply.github.com&gt;;
抄送:&nbsp;"17信管班长邹涵"<2669309696@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ss098/work] Word，PPT，Excel文件上传后无法打开 (#22)





 
已经修改为兼容任意文件格式的正确正则表达式。

**Comment by ss098** [comment]
再次修改了正则表达式，经过测试之前丢失的内容可以正确输出，欢迎再次测试。
