### ISSUE TITLE
建议调整文件命名格式

### ISSUE THREAD

**Issue by if1y** [ss098/work#24]
目前是 姓名+学号 方式，文件排序很混乱
建议改成 学号+姓名
或者在导出的时候自行选择

**Comment by ss098** [comment]
格式：「姓名 + 学号」是我这里的要求，可能会增加导出选项。

**Comment by if1y** [comment]
明白，这个优先级比较低，能实现当然很好，不能也影响不大，辛苦了！

**Comment by ss098** [comment]
已增加自定义导出格式。
