### ISSUE TITLE
hi,请问能否开放 API?

### ISSUE THREAD

**Issue by a77uu** [ss098/work#27]
开放API可以定时创建一个表单并反馈，比如每周一早上使用 CronTab8:30 直接访问 /create 的 API 就可定时创建并反馈表单提交链接.
又如 /delete 就可定期删除表单内容.

**Comment by ss098** [comment]
应用是以 RESTful 架构设计的前后端分离应用，原生支持 HTTP API，刚刚已经提交 Commit 关闭 CSRF Token 验证。

出于应用复杂度的考虑（未引入鉴权机制），暂不支持以后也可能不支持删除操作。

**Comment by a77uu** [comment]
搭建时出现500错误 已在 .env 中设置数据库信息且可以连接
`[2020-07-01 x] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select `forms`.*, (select count(*) from `records` where `forms`.`id` = `records`.`form_id` and `records`.`deleted_at` is null) as `record_count` from `forms` where `forms`.`deleted_at` is null order by `id` desc limit 25) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select `forms`.*, (select count(*) from `records` where `forms`.`id` = `records`.`form_id` and `records`.`deleted_at` is null) as `record_count` from `forms` where `forms`.`deleted_at` is null order by `id` desc limit 25) at /www/wwwroot/work/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) at /www/wwwroot/work/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70)`

**Comment by ss098** [comment]
注意验证 MySQL 账户授权连接地址授权给了 localhost 还是 127.0.0.1。
