### ISSUE TITLE
表单提交可以增加一栏班级代码

### ISSUE THREAD

**Issue by ylwzbk** [ss098/work#29]
作者你好  学校要求 截图要有班级代码  能否增加一个班级栏填写  0191906这种

**Comment by ss098** [comment]
你好，指的是导出时的文件格式为`班级姓名学号.jpg`这种吗？

如果表单内的数据属于同个班级，班级栏一致，可以临时通过以下这个链接导出，替换 `{id}` 为表单 ID。

https://work.qiyichao.cn/recycle/export?id={id}&format=班级namecode

如果属于不同班级或其他场景，请再作回复。

**Comment by ylwzbk** [comment]
有不同班级

**Comment by ss098** [comment]
了解，会择期增加自定义字段。

**Comment by ylwzbk** [comment]
好的 现在还有一种问题就是突然导出不来了 这种提示
![Uploading Screenshot_2020-10-19-21-58-16-915_com.UCMobile.jpg…]()

**Comment by ss098** [comment]
无法查看图片，可以直接描述错误信息。

**Comment by ylwzbk** [comment]
导出显示 Exception
The path "/www/wwwroot/dxx.645ds.com/storage/RJ9Zr94eqkI9LWK86aRsPTQmwbYLvN8g.zip

**Comment by ss098** [comment]
该表单内可能没有实际文件，无法创建压缩包。

**Comment by ylwzbk** [comment]
明白了  ，谢啦
