### ISSUE TITLE
创建表单失败

### ISSUE THREAD

**Issue by BUZHA** [ss098/work#32]
大佬还维护嘛

**Comment by BUZHA** [comment]
node版本v18.12.1，一切正常显示，就是创建表单会失败

**Comment by ss098** [comment]
猜测是后端请求失败，观察一下发送的 API 有什么错误。

**Comment by BUZHA** [comment]
请教下大佬怎么查看，宝塔环境，php版本7.4，node版本v18.会出现以下问题
`
[root@VM-8-8-centos work-master]# npm install
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated image-compressor.js@1.1.4: No longer maintainted, please use `comprossorjs`
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 2013 packages, removed 885 packages, and changed 104 packages in 53s
[root@VM-8-8-centos work-master]# npm run production

> production
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, 255) or calc($value / 255)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
70 │     $value: $value / 255
   │             ^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/utilities/functions.sass 70:13          colorLuminance()
    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()
    node_modules/bulma/sass/utilities/derived-variables.sass 13:17  @import
    node_modules/bulma/sass/utilities/_all.sass 5:9                 @import
    node_modules/bulma/bulma.sass 3:9                               @import
    stdin 3:9                                                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value + 0.055, 1.055) or calc(($value + 0.055) / 1.055)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
74 │       $value: ($value + .055) / 1.055
   │               ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/utilities/functions.sass 74:15          colorLuminance()
    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()
    node_modules/bulma/sass/utilities/derived-variables.sass 13:17  @import
    node_modules/bulma/sass/utilities/_all.sass 5:9                 @import
    node_modules/bulma/bulma.sass 3:9                               @import
    stdin 3:9                                                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, 12.92) or calc($value / 12.92)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
72 │       $value: $value / 12.92
   │               ^^^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/utilities/functions.sass 72:15          colorLuminance()
    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()
    node_modules/bulma/sass/utilities/derived-variables.sass 16:20  @import
    node_modules/bulma/sass/utilities/_all.sass 5:9                 @import
    node_modules/bulma/bulma.sass 3:9                               @import
    stdin 3:9                                                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-1, 2) or calc(-1 / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
74 │       margin-left: calc(#{-1 / 2 * $button-padding-horizontal} - #{$button-border-width})
   │                           ^^^^^^
   ╵
    node_modules/bulma/sass/elements/button.sass 74:27  @import
    node_modules/bulma/sass/elements/_all.sass 4:9      @import
    node_modules/bulma/bulma.sass 5:9                   @import
    stdin 3:9                                           root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($button-padding-horizontal, 4) or calc($button-padding-horizontal / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
75 │       margin-right: $button-padding-horizontal / 4
   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/elements/button.sass 75:21  @import
    node_modules/bulma/sass/elements/_all.sass 4:9      @import
    node_modules/bulma/bulma.sass 5:9                   @import
    stdin 3:9                                           root stylesheet

Warning: 20 repetitive deprecation warnings omitted.

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, 255) or calc($value / 255)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
70 │     $value: $value / 255
   │             ^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/utilities/functions.sass 70:13          colorLuminance()
    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()
    node_modules/bulma/sass/utilities/derived-variables.sass 13:17  @import
    node_modules/bulma/sass/utilities/_all.sass 5:9                 @import
    node_modules/bulma/bulma.sass 3:9                               @import
    stdin 3:9                                                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value + 0.055, 1.055) or calc(($value + 0.055) / 1.055)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
74 │       $value: ($value + .055) / 1.055
   │               ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/utilities/functions.sass 74:15          colorLuminance()
    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()
    node_modules/bulma/sass/utilities/derived-variables.sass 13:17  @import
    node_modules/bulma/sass/utilities/_all.sass 5:9                 @import
    node_modules/bulma/bulma.sass 3:9                               @import
    stdin 3:9                                                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, 12.92) or calc($value / 12.92)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
72 │       $value: $value / 12.92
   │               ^^^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/utilities/functions.sass 72:15          colorLuminance()
    node_modules/bulma/sass/utilities/functions.sass 80:8           findColorInvert()
    node_modules/bulma/sass/utilities/derived-variables.sass 16:20  @import
    node_modules/bulma/sass/utilities/_all.sass 5:9                 @import
    node_modules/bulma/bulma.sass 3:9                               @import
    stdin 3:9                                                       root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-1, 2) or calc(-1 / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
74 │       margin-left: calc(#{-1 / 2 * $button-padding-horizontal} - #{$button-border-width})
   │                           ^^^^^^
   ╵
    node_modules/bulma/sass/elements/button.sass 74:27  @import
    node_modules/bulma/sass/elements/_all.sass 4:9      @import
    node_modules/bulma/bulma.sass 5:9                   @import
    stdin 3:9                                           root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($button-padding-horizontal, 4) or calc($button-padding-horizontal / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
75 │       margin-right: $button-padding-horizontal / 4
   │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/bulma/sass/elements/button.sass 75:21  @import
    node_modules/bulma/sass/elements/_all.sass 4:9      @import
    node_modules/bulma/bulma.sass 5:9                   @import
    stdin 3:9                                           root stylesheet

Warning: 20 repetitive deprecation warnings omitted.



 DONE  Compiled successfully in 14309ms                                                                                22:40:47

                                             Asset      Size  Chunks             Chunk Names
                                      /css/app.css   189 KiB       0  [emitted]  /js/app
                                        /js/app.js   221 KiB       0  [emitted]  /js/app
images/upload.png?ab216f2836d81c9303af90b2f1fee646  3.42 KiB          [emitted]  
[root@VM-8-8-centos work-master]# cp .env.example .env
[root@VM-8-8-centos work-master]# 
[root@VM-8-8-centos work-master]# php artisan key:generate
Application key set successfully.
[root@VM-8-8-centos work-master]# php artisan migrate
Nothing to migrate.
`

**Comment by BUZHA** [comment]
大佬帮我看看http://jt.niancc.cn/  感谢

**Comment by ss098** [comment]
你的网址打不开，尝试降级 Node 16，软件依赖很久没有升级了，我看了下服务器用的是 16 版本，PHP 是 7.4。

**Comment by BUZHA** [comment]
已经测试一遍了，目前返回值是500，还是无厘头http://jt.niancc.cn/

**Comment by ss098** [comment]
需要配置 `.env` 文件打开调试模式，或查看 `storage/logs` 目录下的日志。

    APP_ENV=local
    APP_DEBUG=true
